title: Дата-артель

description: Превращаем архивы в знания

# Эта строка указывает GitHub, какую тему использовать. 
# Он добавляет ее сам при выборе темы через интерфейс, но полезно ее видеть.
theme: jekyll-theme-minimal
# Если вы не меняли тему, можете оставить эту строку закомментированной или удалить.

# Это опциональные настройки для многих тем, чтобы убрать лишние ссылки
show_downloads: false
# github:
 is_project_page: false
